apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-zs2g
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-upkl-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-zs2g@sha256:11a4fdcec00db3d17bf4dbd82d039802c87bcea1817aa6db040f28f26ff01499
        name: container-image
        resources: {}
status: {}
